### ISSUE TITLE
Allow users to choose which timers are saved

### ISSUE THREAD

**Issue by ForeverWinter** [dziemborowicz/hourglass#167] opened 2018-06-04 16:42 UTC
Instead of the "saved timers" list being auto-populated, let users choose which timers are saved by right click --> Add this timer to saved timers

Alternatively, create a new category of saved timers called "favorites" and options of "add to favorites" and "open favorite timers on startup"

**Comment by dziemborowicz** [comment] 2021-09-28 20:45
Closing as a duplicate of #214.

**Closed by dziemborowicz** 2021-09-28 20:45 UTC
Labels: enhancement
