### ISSUE TITLE
Saving a history list of Timer's and activities 

### ISSUE THREAD

**Issue by lilbro1062000** [Dziemborowicz/Hourglass#93] opened 2016-01-27 20:59 UTC
New Enhancement. The ability to store previously created timer's and stops. 

Does not matter if this is a list that can be copied to clipboard. This is useful for keeping track of the multiple tasks you have done with the timer. Maybe have a timer created date time as part of the report.

**Comment by Dziemborowicz** [comment] 2016-01-31 22:24
Duplicate of #70.

**Closed by Dziemborowicz** 2016-01-31 22:24 UTC
Labels: enhancement
