### ISSUE TITLE
Would LOVE to use this but..

### ISSUE THREAD

**Issue by kler01** [dziemborowicz/hourglass#185] opened 2019-04-22 01:16 UTC
The overlay window is too big and it would be really great if there was a way to resize it as small as I need. Maybe with a dynamic layout that follows it.
Right now i'm using "Visual Timer" but it's very annoying since i'm limited to 60m and i can't throw the main app into the status bar for de-clutter once i'm on the small clock in the corner of my screen.

I'm using it to split my work in sessions and the size is very distracting, sadly.
Also it would be nice to be able to pick my own colors for everything, maybe even shape, so that i can make it easy on the eyes and less distracting for me while still being aware that it is always there.

I would switch in a second if i could do that. but great work anyway and thank you for doing this in your spare time, it's great :)

**Comment by kler01** [comment] 2019-04-22 01:19
like, for instance, a small borderless bar that i can freely resize, visually fills itself, can choose bar and text colors and transparency, with the numberical countdown with the typeface of my chosing that i can to align left/center/right and two small icons for start/pause/stop

**Comment by kler01** [comment] 2019-04-22 01:47
![image](https://user-images.githubusercontent.com/14167503/56478660-a9158d00-64b9-11e9-87f7-ee5d47fb8c8c.png)

I did a quick example of how it could look like

**Comment by dziemborowicz** [comment] 2019-04-23 19:48
Duplicate of #90.

**Closed by dziemborowicz** 2019-04-23 19:48 UTC
