### ISSUE TITLE
Add About Page and Links Your Website and GitHub Page

### ISSUE THREAD

**Issue by asjones987** [dziemborowicz/hourglass#162] opened 2018-03-30 13:00 UTC
I could not find it (unless it is just starting meet in the face) and "about" popup page. For those that download the app and need to refresh or want more info  and about page would be nice. Including links to your page 
https://chris.dziemborowicz.com/ 
and to the GitHub page 
https://github.com/dziemborowicz/hourglass

This would be very helpful.  
I opened Hourglass the other day and wanted to find a link to the development and did not see it. I  know others can search like I did, but links to the "official" pages and not some knockoff download site would be nice.

**Comment by asjones987** [comment] 2018-03-30 13:04
Of course add version,  author, copyright, and license information to the about page.
I did see properties on the .exe had the version/copyright info.

**Comment by dziemborowicz** [comment] 2018-04-01 00:37
Duplicate of #78.

**Closed by dziemborowicz** 2018-04-01 00:37 UTC
Labels: duplicate, enhancement
