### ISSUE TITLE
Advanced loopable timers

### ISSUE THREAD

**Issue by DoctorLogiq** [dziemborowicz/hourglass#192] opened 2020-05-03 12:10 UTC
Hi. Firstly, thank you for this fantastic little app, it's the most useful utility on my computer, and I use it daily, and have even recommended it to a few friends.

That being said, I have thought of another use for it, but this would require a new feature.
What I'm looking for is the ability to set up an advanced loop timer. What it would need to do is allow the user to create a list of durations, and the timer would loop through the list, each time it expires it chooses the next duration in the list and restarts using that new duration.

The reason for this is that I'd like to set up a timer for my programming livestreams, which will count down 15 or 20 minutes (yet to decide), then it will be time to take a break... then it will count down 5 minutes for the duration of the break, and then start over.

**Comment by dziemborowicz** [comment] 2020-05-06 01:18
This is a good suggestion that I intend to implement at some point. It's already tracked by #118, but I haven't had the time to update the model for this in years...

**Comment by dziemborowicz** [comment] 2020-05-06 01:18
Closing as a duplicate of #118.

**Closed by dziemborowicz** 2020-05-06 01:18 UTC
Labels: enhancement
