### ISSUE TITLE
Allow smaller window sizes

### ISSUE THREAD

**Issue by panhartstuff** [dziemborowicz/hourglass#158] opened 2018-02-17 15:16 UTC
The window size of this program at its smallest still feels to big and obtrusive for users with a low-range resolution (1366x768).  It'd be extremely helpful to make a feature that allows even smaller window sizes

**Comment by Fironet** [comment] 2018-02-18 17:55
Any ideas for how the UI would change to accommodate? Was curious what it would look like at that res at the smallest window size and it's reaching near the edges as-is with its current padding:

![screenshot](https://user-images.githubusercontent.com/6971981/36354933-a911f594-152f-11e8-83f2-355330c9a47d.png)

Seems fairly compact to me but were you thinking to split the hour/minute/second into new lines? Would pretty much do away with the titlebar visibility but possible I suppose, at least when counting down:

![even smaller](https://user-images.githubusercontent.com/6971981/36354978-42d00ff4-1530-11e8-8474-77d8fabe3901.png)

Obstacle with that is the input UI would have to be re-designed for that scale since the field widths would be impractical in their current implementation.

**Comment by panhartstuff** [comment] 2018-02-18 20:34
![image](https://user-images.githubusercontent.com/34397257/36356462-f2082d46-1524-11e8-9f11-91a332bbc397.png)
I'm thinking of something like the size of PomoDoneApp's mini timer mode, but even slimmer horizontally

I did some edits of what I'm thinking of

![image](https://user-images.githubusercontent.com/34397257/36356503-92bafbba-1525-11e8-8983-0b5c6d05e955.png)

**Comment by Fironet** [comment] 2018-02-19 04:09
I see, so it's vertically you were looking to save space, presumably as you want the window visible at all times while working on things?

How does the PomoDoneApp program handle entering the title and the time in that space btw, by clicking on the two areas and entering new values or is it input separately? I wonder as if the input screen remained the same of Hourglass' current smallest size but could optionally switch to a 'mini' mode when running the UI could be less cramped, input-wise.

**Comment by dziemborowicz** [comment] 2019-04-23 19:48
Duplicate of #90.

**Closed by dziemborowicz** 2019-04-23 19:48 UTC
Labels: enhancement
