### ISSUE TITLE
Vertical height can be more lowered

### ISSUE THREAD

**Issue by ky-japan** [dziemborowicz/hourglass#194] opened 2020-06-08 14:21 UTC
Hello. I am a Japanese "Orzeszek Timer" user and I tried "Hourglass" this time.
And I found that the only inconvenience point of "Hourglass" was that the vertical height cannot be shorter than a certain length.  I want to use "Hourglass" in a small area.
I would be happy if you could address this in the future.
Thank you.

**Comment by dziemborowicz** [comment] 2020-06-09 05:38
Closing as duplicate of #90.

**Closed by dziemborowicz** 2020-06-09 05:38 UTC
