### ISSUE TITLE
Ability to set custom font

### ISSUE THREAD

**Issue by hl2guide** [dziemborowicz/hourglass#172] opened 2018-08-06 20:58 UTC
Please consider adding an option for setting a custom font for the GUI.
_I'd love to be able to set it to a monospace font!_

**Comment by dziemborowicz** [comment] 2018-08-06 21:30
Closing this as a duplicate of https://github.com/dziemborowicz/hourglass/issues/112.

**Closed by dziemborowicz** 2018-08-06 21:30 UTC
Labels: duplicate
